Updating benchmarks workflow

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -26,11 +26,6 @@ defaults:
 
 jobs:
   build:
-    if: github.repository_owner == 'tardis-sn' &&
-      (github.event_name == 'push' ||
-      github.event_name == 'workflow_dispatch' ||
-      (github.event_name == 'pull_request_target' &&
-      contains(github.event.pull_request.labels.*.name, 'benchmarks')))
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -65,6 +60,11 @@ jobs:
         with:
           path: benchmarks/data/kurucz_cd23_chianti_H_He.h5
           key: atom-data
+
+      - name: Copy atom data to refdata
+        run: |
+          mkdir -p tardis-refdata/atom_data
+          cp benchmarks/data/kurucz_cd23_chianti_H_He.h5 tardis-refdata/atom_data/
 
       - name: Setup Mamba
         uses: mamba-org/setup-micromamba@v1
@@ -115,21 +115,18 @@ jobs:
           target-branch: main
           target-directory: .asv
 
-      - name: Compare HEAD with master if PR
+      - name: Run benchmarks
         if: github.event_name == 'pull_request_target'
-        continue-on-error: true # TODO: step failed sporadically while testing
-        run: |
-          asv continuous ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  | tee asv-cont-output.log  
-          if grep -q failed asv-cont-output.log; then 
-            echo "Some benchmarks have errors!"
-            exit 1
-          fi
+        run: asv run --config asv.conf.json
+
+      - run: git remote add upstream https://github.com/KasukabeDefenceForce/tardis.git
+      - run: git fetch upstream master
 
       - name: Compare Master and PR head
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tee asv-compare-output.log
+        run: asv compare upstream/master HEAD --config asv.conf.json | tee asv-compare-output.log
 
       - name: Compare Master and PR head but only show changed results
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --only-changed | tee asv-compare-changed-output.log
+        run: asv compare upstream/master HEAD --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
 
       - name: Benchmarks compare output
         id: asv_pr_vs_master
@@ -142,6 +139,42 @@ jobs:
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
+
+      - name: Run benchmarks for base to head commits of PR
+        if: github.event_name == 'pull_request_target'
+        run: |
+          mkdir -p PR-${{ github.event.number }}
+          cd PR-${{ github.event.number }}
+          asv machine --yes
+          asv run ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tee asv-output-PR.log  
+          if grep -q failed asv-output-PR.log; then 
+            echo "Some benchmarks have failed!"
+            exit 1
+          fi
+
+      - name: Generate Graphs and HTML of PR
+        if: github.event_name == 'pull_request_target'
+        run: |
+          cd PR-${{ github.event.number }}
+          asv publish
+
+      - name: Delete env files of PR
+        if: github.event_name == 'pull_request_target'
+        run: rm -r PR-${{ github.event.number }}/.asv/env
+
+      - name: Push results of PR to results repository
+        if: github.event_name == 'pull_request_target'
+        continue-on-error: true
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN }}
+        with:
+          source-directory: PR-${{ github.event.number }}
+          destination-github-username: tardis-sn
+          destination-repository-name: tardis-benchmarks
+          user-email: tardis.sn.bot@gmail.com
+          target-branch: main
+          target-directory: PR
 
       - name: Find Comment
         if: always() && github.event_name == 'pull_request_target'
@@ -165,6 +198,7 @@ jobs:
             I ran benchmarks as you asked comparing master (${{ github.event.pull_request.base.sha }}) and the latest commit (${{ github.event.pull_request.head.sha }}). 
             Here are the logs produced by ASV.
             Results can also be downloaded as artifacts [**here**](${{ env.URL }}). 
+
             Significantly changed benchmarks:
             <details>
 
@@ -192,6 +226,5 @@ jobs:
           name: asv-benchmark-results-${{ runner.os }}
           path: |
             .asv/results
-            asv-cont-output.log  
             asv-compare-output.log
             asv-compare-changed-output.log
