Trying asish 's pr

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -65,14 +65,13 @@ jobs:
           path: benchmarks/data/kurucz_cd23_chianti_H_He.h5
           key: atom-data
 
-      - name: Copy atom data to refdata
-        run: |
-          mkdir -p tardis-refdata/atom_data
-          cp benchmarks/data/kurucz_cd23_chianti_H_He.h5 tardis-refdata/atom_data/
+      # - name: Copy atom data to refdata
+      #   run: |
+      #     mkdir -p tardis-refdata/atom_data
+      #     cp benchmarks/data/kurucz_cd23_chianti_H_He.h5 tardis-refdata/atom_data/
 
-      # - name: Setup tmate session
-      #   uses: mxschmitt/action-tmate@v3
-
+      # # - name: Setup tmate session
+      # #   uses: mxschmitt/action-tmate@v3
       - name: Setup Mamba
         uses: mamba-org/setup-micromamba@v1
         with:
@@ -100,9 +99,9 @@ jobs:
             exit 1
           fi
 
-      - name: ASV benchmarks
-        if: github.event_name != 'pull_request'
-        run: asv run --bench just-discover
+      # - name: ASV benchmarks
+      #   if: github.event_name != 'pull_request'
+      #   run: asv run --bench just-discover
 
       - name: Generate Graphs and HTML
         if: github.event_name != 'pull_request'
@@ -130,17 +129,17 @@ jobs:
         if: github.event_name == 'pull_request'
         continue-on-error: true # TODO: step failed sporadically while testing
         run: |
-          asv continuous ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}  | tee asv-cont-output.log  
+          asv continuous ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tee asv-cont-output.log  
           if grep -q failed asv-cont-output.log; then 
             echo "Some benchmarks have errors!"
             exit 1
           fi
 
       - name: Compare Master and PR head
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | tee asv-compare-output.log
+        run: asv compare master HEAD --config asv.conf.json | tee asv-compare-output.log
 
       - name: Compare Master and PR head but only show changed results
-        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --only-changed | tee asv-compare-changed-output.log
+        run: asv compare master HEAD --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
 
       - name: Benchmarks compare output
         id: asv_pr_vs_master
@@ -153,6 +152,40 @@ jobs:
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
+
+      - name: Run benchmarks for base to head commits of PR
+        if: github.event_name == 'pull_request_target'
+        run: |
+          mkdir -p PR-${{ github.event.number }}
+          cd PR-${{ github.event.number }}
+          asv run ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | tee asv-output-PR.log  
+          if grep -q failed asv-output-PR.log; then 
+            echo "Some benchmarks have failed!"
+            exit 1
+          fi
+
+      - name: Generate Graphs and HTML of PR
+        if: github.event_name == 'pull_request_target'
+        working-directory: PR-${{ github.event.number }}
+        run: asv publish
+
+      - name: Delete env files of PR
+        if: github.event_name == 'pull_request_target'
+        run: rm -r PR-${{ github.event.number }}/.asv/env
+
+      - name: Push results of PR to results repository
+        if: github.event_name == 'pull_request_target'
+        continue-on-error: true
+        uses: cpina/github-action-push-to-another-repository@main
+        env:
+          API_TOKEN_GITHUB: ${{ secrets.BOT_TOKEN }}
+        with:
+          source-directory: PR-${{ github.event.number }}
+          destination-github-username: tardis-sn
+          destination-repository-name: tardis-benchmarks
+          user-email: tardis.sn.bot@gmail.com
+          target-branch: main
+          target-directory: PR
 
       - name: Find Comment
         if: always() && github.event_name == 'pull_request'
